version: '3'

services:
  app:
    image: dockercalculator:latest
    environment:
      - DATABASE_CONNECTION_STRING="Server=localhost,1433;Database=DockerCalculator;User Id=sa;Password=123456;TrustServerCertificate=true"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 123456
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
